
source = ~/.config/assets/palette/palette.conf

monitor =, 1920x1080@144, auto, 1.00

source = programs.conf
source = style.conf
source = input.conf
source = keys.conf
source = windows.conf
source = plugins.conf
source = wallpaper.conf
