
# TAG:POPUP
$POPUP_CLASS = feh|mpv|pureref|webcamoid|solaar|psensor|qalculate|iwgtk|easyeffects|desktop-portal|rofi|overskride|waypaper|cheatsheet|systemapp
$POPUP_TITLE = Picture-in-Picture
windowrulev2 = tag +popup, class:(?i).*($POPUP_CLASS).*
windowrulev2 = tag +popup, title:(?i).*($POPUP_TITLE).*
windowrulev2 = float, tag:popup
windowrulev2 = focusonactivate, tag:popup

# Specific sizes for our custom popups
windowrulev2 = size 70% 80%, class:^(cheatsheet)$
windowrulev2 = center, class:^(cheatsheet)$
windowrulev2 = size 50% 60%, class:^(systemapp)$
windowrulev2 = center, class:^(systemapp)$

# TAG:FORCED
$FORCED_CLASS = rofi|hyprpolkitagent
# $FORCED_TITLE =
windowrulev2 = tag +forced, class:(?i).*($FORCED_CLASS).*
# windowrulev2 = tag +forced, title:(?i).*($FORCED_TITLE).*
windowrulev2 = stayfocused, tag:forced
windowrulev2 = dimaround, tag:forced

windowrulev2 = suppressevent maximize, class:.*
windowrulev2 = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0
